#!/usr/bin/env bash
# Project quality gates: format, clippy with warnings as errors, the test
# suite, and the vendored palette's own check. Called by
# .githooks/pre-commit for every commit and by .claude/hooks/check-commit.sh
# before Claude's commits; non-zero exit blocks the commit.
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

# Git exports GIT_DIR and friends to a hook; a child that inherits them acts
# on this repository instead of the one it means to. Drop them, as kyu does.
unset GIT_DIR GIT_WORK_TREE GIT_INDEX_FILE GIT_PREFIX GIT_COMMON_DIR

# Standing rule 7: a gate that does not predict the build is not a gate.
# cargo rewrites Cargo.lock; anything rewritten AFTER `git add` is green
# here and absent from the commit, so the tree is fingerprinted either side.
gate_tree_fingerprint() {
  { git status --porcelain; git diff; } | sha256sum | cut -d' ' -f1
}
gate_tree_before=$(gate_tree_fingerprint)

cargo fmt --all --check
cargo clippy --workspace --all-targets -- -D warnings
cargo test --workspace --quiet

# The palette is vendored from kp-themes, never authored here: an edit
# would be silently undone by the next upgrade, and the difference would
# show as a terminal that disagrees with the web [kp-themes scope-128].
# The file says where it came from; a copy that lost that header, or that
# lost a theme, is not a copy of a release.
palette=crates/kp-tui-palette/src/palette.rs
head -1 "$palette" | grep -q '^// GENERATED by kp-themes ' || {
  echo "$palette lost its generated header: it is vendored from a kp-themes release, not written here."
  exit 1
}
themes=$(grep -c '^    Theme {$' "$palette")
[ "$themes" = 22 ] || {
  echo "$palette carries $themes themes; the package ships 22."
  exit 1
}

if [ "$(gate_tree_fingerprint)" != "$gate_tree_before" ]; then
  echo "GATES FAILED — the working tree changed while the gates ran."
  echo "Something rewrote files after they were staged. Re-add and retry."
  exit 1
fi
echo "gates green"
