#!/usr/bin/env bash
# Project quality gates: format, clippy with warnings as errors, the test
# suite, and the vendored palette's own check. Called by
# .githooks/pre-commit for every commit and by .claude/hooks/check-commit.sh
# before Claude's commits; non-zero exit blocks the commit.
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

# Git exports GIT_DIR and friends to a hook; a child that inherits them acts
# on this repository instead of the one it means to. Drop them, as kyu does.
unset GIT_DIR GIT_WORK_TREE GIT_INDEX_FILE GIT_PREFIX GIT_COMMON_DIR

# Standing rule 7: a gate that does not predict the build is not a gate.
# cargo rewrites Cargo.lock; anything rewritten AFTER `git add` is green
# here and absent from the commit, so the tree is fingerprinted either side.
gate_tree_fingerprint() {
  { git status --porcelain; git diff; } | sha256sum | cut -d' ' -f1
}
gate_tree_before=$(gate_tree_fingerprint)

cargo fmt --all --check
cargo clippy --workspace --all-targets -- -D warnings
cargo test --workspace --quiet

# The palette is vendored from kp-themes, never authored here: an edit
# would be silently undone by the next upgrade, and the difference would
# show as a terminal that disagrees with the web [kp-themes scope-128].
# Since 7.0.0 the copy is pinned to a release rather than merely shaped
# like one: vendor/PIN names the version and the checksum the release
# published, and this compares the bytes on disk against it.
vendor=crates/kp-tui-palette/vendor/kp-tui-palette.rs
pin=crates/kp-tui-palette/vendor/PIN
[ -f "$pin" ] || {
  echo "$pin is missing: the vendored palette has to say which release it came from."
  exit 1
}
pin_version=$(sed -n 's/^version = //p' "$pin")
pin_sha=$(sed -n 's/^sha256 = //p' "$pin")
have_sha=$(sha256sum "$vendor" | cut -d' ' -f1)
[ "$have_sha" = "$pin_sha" ] || {
  echo "$vendor does not match the release it is pinned to ($pin_version)."
  echo "  pinned:  $pin_sha"
  echo "  on disk: $have_sha"
  echo "It is vendored, not written here. Re-download it, or move the pin on purpose."
  exit 1
}
head -1 "$vendor" | grep -q "^// GENERATED by kp-themes $pin_version " || {
  echo "$vendor says it came from a different release than $pin names."
  exit 1
}
themes=$(grep -c '^    Theme {$' "$vendor")
[ "$themes" = 22 ] || {
  echo "$vendor carries $themes themes; the package ships 22."
  exit 1
}

if [ "$(gate_tree_fingerprint)" != "$gate_tree_before" ]; then
  echo "GATES FAILED — the working tree changed while the gates ran."
  echo "Something rewrote files after they were staged. Re-add and retry."
  exit 1
fi
echo "gates green"
