// GENERATED by kp-themes 7.0.0 (gates/generate-tui-palette.mjs). Do not edit.
//
// Every theme's colours, as the terminal receives them. The anatomy —
// border glyphs, case, prefixes, the cursor, the reveal — is judgement
// and lives in kp-tui, hand-written. This file is data.

pub const KP_THEMES_VERSION: &str = "7.0.0";

/// A colour as three bytes; a terminal at a lower depth maps it itself.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Rgb(pub u8, pub u8, pub u8);

/// What a colour is FOR, which is what a sixteen-colour terminal needs
/// in order to fall back without losing the difference between a plate
/// and the ink on it.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Role {
    Surface,
    Ink,
    Fill,
    OnFill,
    MutedInk,
    Line,
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Palette<C> {
    /// `--background`
    pub background: C,
    /// `--foreground`
    pub foreground: C,
    /// `--card`
    pub card: C,
    /// `--card-foreground`
    pub card_foreground: C,
    /// `--popover`
    pub popover: C,
    /// `--popover-foreground`
    pub popover_foreground: C,
    /// `--primary`
    pub primary: C,
    /// `--primary-foreground`
    pub primary_foreground: C,
    /// `--primary-hover`
    pub primary_hover: C,
    /// `--primary-active`
    pub primary_active: C,
    /// `--primary-disabled`
    pub primary_disabled: C,
    /// `--secondary`
    pub secondary: C,
    /// `--secondary-foreground`
    pub secondary_foreground: C,
    /// `--secondary-active`
    pub secondary_active: C,
    /// `--muted`
    pub muted: C,
    /// `--muted-foreground`
    pub muted_foreground: C,
    /// `--accent`
    pub accent: C,
    /// `--accent-foreground`
    pub accent_foreground: C,
    /// `--destructive`
    pub destructive: C,
    /// `--destructive-foreground`
    pub destructive_foreground: C,
    /// `--success`
    pub success: C,
    /// `--success-foreground`
    pub success_foreground: C,
    /// `--warning`
    pub warning: C,
    /// `--warning-foreground`
    pub warning_foreground: C,
    /// `--info`
    pub info: C,
    /// `--info-foreground`
    pub info_foreground: C,
    /// `--border`
    pub border: C,
    /// `--border-strong`
    pub border_strong: C,
    /// `--ring`
    pub ring: C,
    /// `--chart-1`
    pub chart_1: C,
    /// `--chart-2`
    pub chart_2: C,
    /// `--chart-3`
    pub chart_3: C,
    /// `--chart-4`
    pub chart_4: C,
    /// `--chart-5`
    pub chart_5: C,
    /// `--code-keyword`
    pub code_keyword: C,
    /// `--code-string`
    pub code_string: C,
}

impl<C: Copy> Palette<C> {
    /// The same shape in another colour type: resolve each field for
    /// the terminal at hand.
    pub fn map<D>(&self, f: impl Fn(Role, C) -> D) -> Palette<D> {
        Palette {
            background: f(Role::Surface, self.background),
            foreground: f(Role::Ink, self.foreground),
            card: f(Role::Surface, self.card),
            card_foreground: f(Role::Ink, self.card_foreground),
            popover: f(Role::Surface, self.popover),
            popover_foreground: f(Role::Ink, self.popover_foreground),
            primary: f(Role::Fill, self.primary),
            primary_foreground: f(Role::OnFill, self.primary_foreground),
            primary_hover: f(Role::Fill, self.primary_hover),
            primary_active: f(Role::Fill, self.primary_active),
            primary_disabled: f(Role::Fill, self.primary_disabled),
            secondary: f(Role::Surface, self.secondary),
            secondary_foreground: f(Role::Ink, self.secondary_foreground),
            secondary_active: f(Role::Surface, self.secondary_active),
            muted: f(Role::Surface, self.muted),
            muted_foreground: f(Role::MutedInk, self.muted_foreground),
            accent: f(Role::Fill, self.accent),
            accent_foreground: f(Role::OnFill, self.accent_foreground),
            destructive: f(Role::Fill, self.destructive),
            destructive_foreground: f(Role::OnFill, self.destructive_foreground),
            success: f(Role::Fill, self.success),
            success_foreground: f(Role::OnFill, self.success_foreground),
            warning: f(Role::Fill, self.warning),
            warning_foreground: f(Role::OnFill, self.warning_foreground),
            info: f(Role::Fill, self.info),
            info_foreground: f(Role::OnFill, self.info_foreground),
            border: f(Role::Line, self.border),
            border_strong: f(Role::Line, self.border_strong),
            ring: f(Role::Line, self.ring),
            chart_1: f(Role::Fill, self.chart_1),
            chart_2: f(Role::Fill, self.chart_2),
            chart_3: f(Role::Fill, self.chart_3),
            chart_4: f(Role::Fill, self.chart_4),
            chart_5: f(Role::Fill, self.chart_5),
            code_keyword: f(Role::Ink, self.code_keyword),
            code_string: f(Role::Ink, self.code_string),
        }
    }
}

/// One theme as the package ships it.
#[derive(Clone, Copy, Debug)]
pub struct Theme {
    pub name: &'static str,
    pub dark: bool,
    /// `--fx-duration`, in milliseconds.
    pub fx_duration_ms: u32,
    pub palette: Palette<Rgb>,
}

/// Every theme, in the package's own order (`themes/order.json`).
pub const THEMES: [Theme; 22] = [
    Theme {
        name: "formal",
        dark: false,
        fx_duration_ms: 180,
        palette: Palette {
            background: Rgb(249, 248, 245),             // hsl(40, 25%, 97%)
            foreground: Rgb(23, 30, 43),                // hsl(220, 30%, 13%)
            card: Rgb(253, 253, 252),                   // hsl(40, 30%, 99%)
            card_foreground: Rgb(23, 30, 43),           // hsl(220, 30%, 13%)
            popover: Rgb(253, 253, 252),                // hsl(40, 30%, 99%)
            popover_foreground: Rgb(23, 30, 43),        // hsl(220, 30%, 13%)
            primary: Rgb(34, 54, 89),                   // hsl(218, 45%, 24%)
            primary_foreground: Rgb(250, 248, 245),     // hsl(40, 30%, 97%)
            primary_hover: Rgb(19, 39, 73),             // hsl(218, 58%, 18%)
            primary_active: Rgb(6, 23, 55),             // hsl(219, 81%, 12%)
            primary_disabled: Rgb(57, 79, 116),         // hsl(218, 34%, 34%)
            secondary: Rgb(234, 231, 225),              // hsl(40, 18%, 90%)
            secondary_foreground: Rgb(34, 42, 57),      // hsl(220, 25%, 18%)
            secondary_active: Rgb(196, 193, 187),       // hsl(40, 7%, 75%)
            muted: Rgb(235, 233, 229),                  // hsl(40, 15%, 91%)
            muted_foreground: Rgb(81, 88, 103),         // hsl(220, 12%, 36%)
            accent: Rgb(237, 224, 212),                 // hsl(30, 40%, 88%)
            accent_foreground: Rgb(81, 52, 31),         // hsl(25, 45%, 22%)
            destructive: Rgb(163, 41, 41),              // hsl(0, 60%, 40%)
            destructive_foreground: Rgb(250, 248, 245), // hsl(40, 30%, 97%)
            success: Rgb(205, 229, 213),                // hsl(140, 32%, 85%)
            success_foreground: Rgb(39, 109, 62),       // hsl(140, 47%, 29%)
            warning: Rgb(234, 220, 200),                // hsl(35, 45%, 85%)
            warning_foreground: Rgb(131, 90, 33),       // hsl(35, 60%, 32%)
            info: Rgb(205, 216, 229),                   // hsl(212, 32%, 85%)
            info_foreground: Rgb(51, 94, 142),          // hsl(212, 47%, 38%)
            border: Rgb(222, 219, 211),                 // hsl(40, 15%, 85%)
            border_strong: Rgb(127, 138, 159),          // hsl(220, 14%, 56%)
            ring: Rgb(56, 90, 148),                     // hsl(218, 45%, 40%)
            chart_1: Rgb(49, 79, 129),                  // hsl(218, 45%, 35%)
            chart_2: Rgb(178, 125, 52),                 // hsl(35, 55%, 45%)
            chart_3: Rgb(107, 126, 68),                 // hsl(80, 30%, 38%)
            chart_4: Rgb(178, 83, 52),                  // hsl(15, 55%, 45%)
            chart_5: Rgb(123, 135, 157),                // hsl(220, 15%, 55%)
            code_keyword: Rgb(49, 79, 129),             // hsl(218, 45%, 35%)
            code_string: Rgb(150, 106, 44),             // hsl(35, 55%, 38%)
        },
    },
    Theme {
        name: "light",
        dark: false,
        fx_duration_ms: 150,
        palette: Palette {
            background: Rgb(255, 255, 255),             // hsl(0, 0%, 100%)
            foreground: Rgb(23, 27, 38),                // hsl(224, 25%, 12%)
            card: Rgb(255, 255, 255),                   // hsl(0, 0%, 100%)
            card_foreground: Rgb(23, 27, 38),           // hsl(224, 25%, 12%)
            popover: Rgb(255, 255, 255),                // hsl(0, 0%, 100%)
            popover_foreground: Rgb(23, 27, 38),        // hsl(224, 25%, 12%)
            primary: Rgb(53, 46, 184),                  // hsl(243, 60%, 45%)
            primary_foreground: Rgb(255, 255, 255),     // hsl(0, 0%, 100%)
            primary_hover: Rgb(42, 20, 163),            // hsl(249, 78%, 36%)
            primary_active: Rgb(33, 0, 143),            // hsl(254, 100%, 28%)
            primary_disabled: Rgb(71, 76, 215),         // hsl(238, 64%, 56%)
            secondary: Rgb(237, 239, 242),              // hsl(220, 15%, 94%)
            secondary_foreground: Rgb(41, 46, 61),      // hsl(224, 20%, 20%)
            secondary_active: Rgb(199, 201, 204),       // hsl(220, 4%, 79%)
            muted: Rgb(240, 242, 244),                  // hsl(220, 15%, 95%)
            muted_foreground: Rgb(85, 91, 109),         // hsl(224, 12%, 38%)
            accent: Rgb(218, 245, 251),                 // hsl(190, 80%, 92%)
            accent_foreground: Rgb(14, 57, 78),         // hsl(200, 70%, 18%)
            destructive: Rgb(184, 30, 30),              // hsl(0, 72%, 42%)
            destructive_foreground: Rgb(255, 255, 255), // hsl(0, 0%, 100%)
            success: Rgb(208, 241, 224),                // hsl(150, 55%, 88%)
            success_foreground: Rgb(21, 117, 69),       // hsl(150, 70%, 27%)
            warning: Rgb(250, 231, 198),                // hsl(38, 85%, 88%)
            warning_foreground: Rgb(143, 90, 0),        // hsl(38, 100%, 28%)
            info: Rgb(201, 228, 247),                   // hsl(205, 75%, 88%)
            info_foreground: Rgb(9, 103, 170),          // hsl(205, 90%, 35%)
            border: Rgb(220, 223, 228),                 // hsl(220, 13%, 88%)
            border_strong: Rgb(134, 142, 156),          // hsl(220, 10%, 57%)
            ring: Rgb(78, 71, 209),                     // hsl(243, 60%, 55%)
            chart_1: Rgb(78, 71, 209),                  // hsl(243, 60%, 55%)
            chart_2: Rgb(31, 150, 173),                 // hsl(190, 70%, 40%)
            chart_3: Rgb(44, 150, 97),                  // hsl(150, 55%, 38%)
            chart_4: Rgb(220, 122, 24),                 // hsl(30, 80%, 48%)
            chart_5: Rgb(204, 51, 128),                 // hsl(330, 60%, 50%)
            code_keyword: Rgb(78, 71, 209),             // hsl(243, 60%, 55%)
            code_string: Rgb(26, 127, 147),             // hsl(190, 70%, 34%)
        },
    },
    Theme {
        name: "dark",
        dark: true,
        fx_duration_ms: 220,
        palette: Palette {
            background: Rgb(11, 12, 15),              // hsl(220, 16%, 5%)
            foreground: Rgb(237, 240, 243),           // hsl(205, 20%, 94%)
            card: Rgb(17, 19, 23),                    // hsl(220, 15%, 8%)
            card_foreground: Rgb(237, 240, 243),      // hsl(205, 20%, 94%)
            popover: Rgb(21, 24, 30),                 // hsl(220, 16%, 10%)
            popover_foreground: Rgb(237, 240, 243),   // hsl(205, 20%, 94%)
            primary: Rgb(233, 238, 241),              // hsl(200, 22%, 93%)
            primary_foreground: Rgb(12, 14, 19),      // hsl(220, 24%, 6%)
            primary_hover: Rgb(211, 222, 227),        // hsl(200, 22%, 86%)
            primary_active: Rgb(187, 203, 211),       // hsl(200, 22%, 78%)
            primary_disabled: Rgb(203, 208, 210),     // hsl(200, 8%, 81%)
            secondary: Rgb(26, 29, 35),               // hsl(220, 16%, 12%)
            secondary_foreground: Rgb(181, 189, 197), // hsl(210, 12%, 74%)
            secondary_active: Rgb(56, 59, 67),        // hsl(220, 9%, 24%)
            muted: Rgb(24, 27, 33),                   // hsl(220, 16%, 11%)
            muted_foreground: Rgb(123, 134, 147),     // hsl(214, 10%, 53%)
            accent: Rgb(28, 31, 38),                  // hsl(220, 16%, 13%)
            accent_foreground: Rgb(231, 235, 239),    // hsl(205, 20%, 92%)
            destructive: Rgb(248, 110, 89),           // hsl(8, 92%, 66%)
            destructive_foreground: Rgb(33, 11, 8),   // hsl(8, 60%, 8%)
            success: Rgb(24, 57, 44),                 // hsl(155, 40%, 16%)
            success_foreground: Rgb(67, 219, 156),    // hsl(155, 68%, 56%)
            warning: Rgb(65, 47, 16),                 // hsl(38, 60%, 16%)
            warning_foreground: Rgb(245, 181, 71),    // hsl(38, 90%, 62%)
            info: Rgb(18, 56, 63),                    // hsl(190, 55%, 16%)
            info_foreground: Rgb(136, 224, 242),      // hsl(190, 80%, 74%)
            border: Rgb(38, 43, 49),                  // hsl(214, 12%, 17%)
            border_strong: Rgb(67, 75, 86),           // hsl(214, 12%, 30%)
            ring: Rgb(90, 220, 246),                  // hsl(190, 90%, 66%)
            chart_1: Rgb(65, 226, 251),               // hsl(188, 96%, 62%)
            chart_2: Rgb(174, 110, 247),              // hsl(268, 90%, 70%)
            chart_3: Rgb(248, 89, 200),               // hsl(318, 92%, 66%)
            chart_4: Rgb(189, 243, 63),               // hsl(78, 88%, 60%)
            chart_5: Rgb(233, 238, 241),              // hsl(200, 22%, 93%)
            code_keyword: Rgb(65, 226, 251),          // hsl(188, 96%, 62%)
            code_string: Rgb(174, 110, 247),          // hsl(268, 90%, 70%)
        },
    },
    Theme {
        name: "cyberpunk",
        dark: true,
        fx_duration_ms: 180,
        palette: Palette {
            background: Rgb(10, 9, 11),               // hsl(270, 9%, 4%)
            foreground: Rgb(215, 213, 204),           // hsl(50, 12%, 82%)
            card: Rgb(19, 18, 22),                    // hsl(255, 10%, 8%)
            card_foreground: Rgb(215, 213, 204),      // hsl(50, 12%, 82%)
            popover: Rgb(24, 23, 28),                 // hsl(255, 10%, 10%)
            popover_foreground: Rgb(215, 213, 204),   // hsl(50, 12%, 82%)
            primary: Rgb(253, 236, 8),                // hsl(56, 98%, 51%)
            primary_foreground: Rgb(17, 16, 8),       // hsl(53, 36%, 5%)
            primary_hover: Rgb(255, 255, 61),         // hsl(60, 100%, 62%)
            primary_active: Rgb(249, 251, 177),       // hsl(62, 91%, 84%)
            primary_disabled: Rgb(224, 206, 0),       // hsl(55, 100%, 44%)
            secondary: Rgb(34, 32, 39),               // hsl(255, 10%, 14%)
            secondary_foreground: Rgb(221, 220, 212), // hsl(50, 12%, 85%)
            secondary_active: Rgb(64, 62, 70),        // hsl(255, 6%, 26%)
            muted: Rgb(29, 28, 33),                   // hsl(255, 8%, 12%)
            muted_foreground: Rgb(149, 146, 131),     // hsl(50, 8%, 55%)
            accent: Rgb(0, 238, 255),                 // hsl(184, 100%, 50%)
            accent_foreground: Rgb(0, 37, 41),        // hsl(185, 100%, 8%)
            destructive: Rgb(238, 58, 79),            // hsl(353, 84%, 58%)
            destructive_foreground: Rgb(29, 7, 10),   // hsl(353, 60%, 7%)
            success: Rgb(8, 73, 41),                  // hsl(150, 80%, 16%)
            success_foreground: Rgb(37, 244, 140),    // hsl(150, 90%, 55%)
            warning: Rgb(87, 46, 5),                  // hsl(30, 90%, 18%)
            warning_foreground: Rgb(255, 187, 51),    // hsl(40, 100%, 60%)
            info: Rgb(8, 63, 73),                     // hsl(190, 80%, 16%)
            info_foreground: Rgb(26, 240, 255),       // hsl(184, 100%, 55%)
            border: Rgb(65, 62, 16),                  // hsl(56, 60%, 16%)
            border_strong: Rgb(150, 144, 64),         // hsl(56, 40%, 42%)
            ring: Rgb(253, 236, 8),                   // hsl(56, 98%, 51%)
            chart_1: Rgb(253, 236, 8),                // hsl(56, 98%, 51%)
            chart_2: Rgb(0, 238, 255),                // hsl(184, 100%, 50%)
            chart_3: Rgb(239, 77, 96),                // hsl(353, 84%, 62%)
            chart_4: Rgb(161, 102, 255),              // hsl(263, 100%, 70%)
            chart_5: Rgb(215, 213, 204),              // hsl(50, 12%, 82%)
            code_keyword: Rgb(253, 236, 8),           // hsl(56, 98%, 51%)
            code_string: Rgb(0, 238, 255),            // hsl(184, 100%, 50%)
        },
    },
    Theme {
        name: "synthwave",
        dark: true,
        fx_duration_ms: 220,
        palette: Palette {
            background: Rgb(14, 2, 34),               // hsl(263, 89%, 7%)
            foreground: Rgb(224, 209, 255),           // hsl(260, 100%, 91%)
            card: Rgb(38, 35, 52),                    // hsl(250, 20%, 17%)
            card_foreground: Rgb(224, 209, 255),      // hsl(260, 100%, 91%)
            popover: Rgb(43, 34, 58),                 // hsl(262, 27%, 18%)
            popover_foreground: Rgb(224, 209, 255),   // hsl(260, 100%, 91%)
            primary: Rgb(255, 71, 130),               // hsl(341, 100%, 64%)
            primary_foreground: Rgb(14, 2, 34),       // hsl(263, 89%, 7%)
            primary_hover: Rgb(255, 92, 146),         // hsl(340, 100%, 68%)
            primary_active: Rgb(239, 129, 165),       // hsl(340, 77%, 72%)
            primary_disabled: Rgb(223, 32, 105),      // hsl(337, 75%, 50%)
            secondary: Rgb(38, 35, 52),               // hsl(250, 20%, 17%)
            secondary_foreground: Rgb(224, 209, 255), // hsl(260, 100%, 91%)
            secondary_active: Rgb(67, 64, 84),        // hsl(249, 13%, 29%)
            muted: Rgb(32, 28, 44),                   // hsl(255, 22%, 14%)
            muted_foreground: Rgb(158, 144, 208),     // hsl(253, 41%, 69%)
            accent: Rgb(52, 249, 245),                // hsl(179, 94%, 59%)
            accent_foreground: Rgb(0, 25, 25),        // hsl(178, 100%, 5%)
            destructive: Rgb(254, 67, 80),            // hsl(356, 99%, 63%)
            destructive_foreground: Rgb(39, 2, 4),    // hsl(356, 90%, 8%)
            success: Rgb(14, 57, 39),                 // hsl(155, 60%, 14%)
            success_foreground: Rgb(116, 241, 185),   // hsl(153, 82%, 70%)
            warning: Rgb(65, 55, 16),                 // hsl(48, 60%, 16%)
            warning_foreground: Rgb(253, 221, 93),    // hsl(48, 98%, 68%)
            info: Rgb(11, 61, 60),                    // hsl(179, 70%, 14%)
            info_foreground: Rgb(52, 249, 245),       // hsl(179, 94%, 59%)
            border: Rgb(81, 31, 81),                  // hsl(300, 45%, 22%)
            border_strong: Rgb(200, 65, 171),         // hsl(313, 55%, 52%)
            ring: Rgb(52, 249, 245),                  // hsl(179, 94%, 59%)
            chart_1: Rgb(255, 71, 130),               // hsl(341, 100%, 64%)
            chart_2: Rgb(52, 249, 245),               // hsl(179, 94%, 59%)
            chart_3: Rgb(253, 221, 93),               // hsl(48, 98%, 68%)
            chart_4: Rgb(155, 112, 255),              // hsl(258, 100%, 72%)
            chart_5: Rgb(224, 209, 255),              // hsl(260, 100%, 91%)
            code_keyword: Rgb(255, 71, 130),          // hsl(341, 100%, 64%)
            code_string: Rgb(52, 249, 245),           // hsl(179, 94%, 59%)
        },
    },
    Theme {
        name: "pastel",
        dark: false,
        fx_duration_ms: 220,
        palette: Palette {
            background: Rgb(249, 244, 251),             // hsl(285, 45%, 97%)
            foreground: Rgb(57, 38, 64),                // hsl(285, 25%, 20%)
            card: Rgb(255, 255, 255),                   // hsl(0, 0%, 100%)
            card_foreground: Rgb(57, 38, 64),           // hsl(285, 25%, 20%)
            popover: Rgb(255, 255, 255),                // hsl(0, 0%, 100%)
            popover_foreground: Rgb(57, 38, 64),        // hsl(285, 25%, 20%)
            primary: Rgb(166, 48, 107),                 // hsl(330, 55%, 42%)
            primary_foreground: Rgb(253, 247, 250),     // hsl(330, 60%, 98%)
            primary_hover: Rgb(147, 27, 91),            // hsl(328, 69%, 34%)
            primary_active: Rgb(128, 0, 74),            // hsl(325, 100%, 25%)
            primary_disabled: Rgb(198, 78, 134),        // hsl(332, 51%, 54%)
            secondary: Rgb(225, 238, 244),              // hsl(200, 45%, 92%)
            secondary_foreground: Rgb(36, 56, 76),      // hsl(210, 35%, 22%)
            secondary_active: Rgb(188, 199, 205),       // hsl(200, 15%, 77%)
            muted: Rgb(237, 230, 240),                  // hsl(285, 25%, 92%)
            muted_foreground: Rgb(103, 85, 109),        // hsl(285, 12%, 38%)
            accent: Rgb(212, 237, 224),                 // hsl(150, 40%, 88%)
            accent_foreground: Rgb(22, 59, 47),         // hsl(160, 45%, 16%)
            destructive: Rgb(185, 39, 51),              // hsl(355, 65%, 44%)
            destructive_foreground: Rgb(253, 246, 247), // hsl(355, 70%, 98%)
            success: Rgb(200, 234, 217),                // hsl(150, 45%, 85%)
            success_foreground: Rgb(29, 114, 71),       // hsl(150, 60%, 28%)
            warning: Rgb(238, 220, 196),                // hsl(35, 55%, 85%)
            warning_foreground: Rgb(134, 88, 24),       // hsl(35, 70%, 31%)
            info: Rgb(209, 201, 232),                   // hsl(255, 40%, 85%)
            info_foreground: Rgb(92, 57, 198),          // hsl(255, 55%, 50%)
            border: Rgb(226, 214, 230),                 // hsl(285, 25%, 87%)
            border_strong: Rgb(169, 121, 169),          // hsl(300, 22%, 57%)
            ring: Rgb(200, 65, 133),                    // hsl(330, 55%, 52%)
            chart_1: Rgb(203, 77, 140),                 // hsl(330, 55%, 55%)
            chart_2: Rgb(59, 155, 123),                 // hsl(160, 45%, 42%)
            chart_3: Rgb(71, 140, 209),                 // hsl(210, 60%, 55%)
            chart_4: Rgb(184, 125, 0),                  // hsl(41, 100%, 36%)
            chart_5: Rgb(153, 102, 204),                // hsl(270, 50%, 60%)
            code_keyword: Rgb(200, 65, 133),            // hsl(330, 55%, 52%)
            code_string: Rgb(49, 129, 103),             // hsl(160, 45%, 35%)
        },
    },
    Theme {
        name: "terminal",
        dark: true,
        fx_duration_ms: 90,
        palette: Palette {
            background: Rgb(11, 14, 11),              // hsl(120, 10%, 5%)
            foreground: Rgb(104, 243, 104),           // hsl(120, 85%, 68%)
            card: Rgb(15, 20, 15),                    // hsl(120, 14%, 7%)
            card_foreground: Rgb(104, 243, 104),      // hsl(120, 85%, 68%)
            popover: Rgb(15, 20, 15),                 // hsl(120, 14%, 7%)
            popover_foreground: Rgb(104, 243, 104),   // hsl(120, 85%, 68%)
            primary: Rgb(13, 242, 13),                // hsl(120, 90%, 50%)
            primary_foreground: Rgb(0, 20, 0),        // hsl(120, 100%, 4%)
            primary_hover: Rgb(49, 255, 46),          // hsl(119, 100%, 59%)
            primary_active: Rgb(135, 245, 128),       // hsl(116, 85%, 73%)
            primary_disabled: Rgb(0, 219, 0),         // hsl(120, 100%, 43%)
            secondary: Rgb(19, 27, 19),               // hsl(120, 16%, 9%)
            secondary_foreground: Rgb(159, 223, 159), // hsl(120, 50%, 75%)
            secondary_active: Rgb(45, 52, 45),        // hsl(120, 8%, 19%)
            muted: Rgb(23, 28, 23),                   // hsl(120, 8%, 10%)
            muted_foreground: Rgb(134, 182, 134),     // hsl(120, 25%, 62%)
            accent: Rgb(223, 242, 13),                // hsl(65, 90%, 50%)
            accent_foreground: Rgb(28, 31, 0),        // hsl(65, 100%, 6%)
            destructive: Rgb(245, 71, 71),            // hsl(0, 90%, 62%)
            destructive_foreground: Rgb(31, 0, 0),    // hsl(0, 100%, 6%)
            success: Rgb(7, 90, 7),                   // hsl(120, 85%, 19%)
            success_foreground: Rgb(0, 224, 0),       // hsl(120, 100%, 44%)
            warning: Rgb(85, 92, 5),                  // hsl(65, 90%, 19%)
            warning_foreground: Rgb(201, 219, 0),     // hsl(65, 100%, 43%)
            info: Rgb(19, 78, 48),                    // hsl(150, 60%, 19%)
            info_foreground: Rgb(29, 205, 117),       // hsl(150, 75%, 46%)
            border: Rgb(37, 55, 37),                  // hsl(120, 20%, 18%)
            border_strong: Rgb(61, 113, 61),          // hsl(120, 30%, 34%)
            ring: Rgb(13, 242, 13),                   // hsl(120, 90%, 50%)
            chart_1: Rgb(13, 242, 13),                // hsl(120, 90%, 50%)
            chart_2: Rgb(60, 221, 167),               // hsl(160, 70%, 55%)
            chart_3: Rgb(222, 238, 43),               // hsl(65, 85%, 55%)
            chart_4: Rgb(71, 209, 209),               // hsl(180, 60%, 55%)
            chart_5: Rgb(163, 194, 163),              // hsl(120, 20%, 70%)
            code_keyword: Rgb(13, 242, 13),           // hsl(120, 90%, 50%)
            code_string: Rgb(60, 221, 167),           // hsl(160, 70%, 55%)
        },
    },
    Theme {
        name: "forest",
        dark: false,
        fx_duration_ms: 200,
        palette: Palette {
            background: Rgb(246, 244, 238),             // hsl(42, 32%, 95%)
            foreground: Rgb(26, 46, 39),                // hsl(160, 28%, 14%)
            card: Rgb(252, 251, 248),                   // hsl(42, 38%, 98%)
            card_foreground: Rgb(26, 46, 39),           // hsl(160, 28%, 14%)
            popover: Rgb(252, 251, 248),                // hsl(42, 38%, 98%)
            popover_foreground: Rgb(26, 46, 39),        // hsl(160, 28%, 14%)
            primary: Rgb(35, 87, 68),                   // hsl(158, 42%, 24%)
            primary_foreground: Rgb(249, 246, 241),     // hsl(42, 40%, 96%)
            primary_hover: Rgb(16, 70, 52),             // hsl(160, 62%, 17%)
            primary_active: Rgb(0, 56, 38),             // hsl(161, 100%, 11%)
            primary_disabled: Rgb(62, 112, 92),         // hsl(156, 29%, 34%)
            secondary: Rgb(230, 225, 214),              // hsl(42, 24%, 87%)
            secondary_foreground: Rgb(35, 57, 50),      // hsl(160, 24%, 18%)
            secondary_active: Rgb(191, 187, 176),       // hsl(42, 11%, 72%)
            muted: Rgb(233, 229, 221),                  // hsl(42, 20%, 89%)
            muted_foreground: Rgb(76, 97, 90),          // hsl(160, 12%, 34%)
            accent: Rgb(239, 215, 200),                 // hsl(24, 55%, 86%)
            accent_foreground: Rgb(87, 46, 25),         // hsl(20, 55%, 22%)
            destructive: Rgb(165, 56, 39),              // hsl(8, 62%, 40%)
            destructive_foreground: Rgb(250, 247, 244), // hsl(30, 40%, 97%)
            success: Rgb(194, 229, 212),                // hsl(150, 40%, 83%)
            success_foreground: Rgb(32, 111, 71),       // hsl(150, 55%, 28%)
            warning: Rgb(235, 212, 188),                // hsl(30, 55%, 83%)
            warning_foreground: Rgb(134, 79, 24),       // hsl(30, 70%, 31%)
            info: Rgb(192, 218, 231),                   // hsl(200, 45%, 83%)
            info_foreground: Rgb(33, 98, 131),          // hsl(200, 60%, 32%)
            border: Rgb(214, 208, 194),                 // hsl(42, 20%, 80%)
            border_strong: Rgb(96, 144, 128),           // hsl(160, 20%, 47%)
            ring: Rgb(50, 123, 96),                     // hsl(158, 42%, 34%)
            chart_1: Rgb(47, 116, 91),                  // hsl(158, 42%, 32%)
            chart_2: Rgb(195, 99, 34),                  // hsl(24, 70%, 45%)
            chart_3: Rgb(54, 125, 161),                 // hsl(200, 50%, 42%)
            chart_4: Rgb(99, 131, 63),                  // hsl(88, 35%, 38%)
            chart_5: Rgb(143, 120, 86),                 // hsl(35, 25%, 45%)
            code_keyword: Rgb(47, 116, 91),             // hsl(158, 42%, 32%)
            code_string: Rgb(178, 90, 31),              // hsl(24, 70%, 41%)
        },
    },
    Theme {
        name: "high-contrast",
        dark: false,
        fx_duration_ms: 120,
        palette: Palette {
            background: Rgb(255, 255, 255),             // hsl(0, 0%, 100%)
            foreground: Rgb(0, 0, 0),                   // hsl(0, 0%, 0%)
            card: Rgb(255, 255, 255),                   // hsl(0, 0%, 100%)
            card_foreground: Rgb(0, 0, 0),              // hsl(0, 0%, 0%)
            popover: Rgb(255, 255, 255),                // hsl(0, 0%, 100%)
            popover_foreground: Rgb(0, 0, 0),           // hsl(0, 0%, 0%)
            primary: Rgb(0, 51, 153),                   // hsl(220, 100%, 30%)
            primary_foreground: Rgb(255, 255, 255),     // hsl(0, 0%, 100%)
            primary_hover: Rgb(0, 31, 133),             // hsl(226, 100%, 26%)
            primary_active: Rgb(0, 4, 112),             // hsl(238, 100%, 22%)
            primary_disabled: Rgb(27, 79, 182),         // hsl(220, 74%, 41%)
            secondary: Rgb(255, 255, 255),              // hsl(0, 0%, 100%)
            secondary_foreground: Rgb(0, 0, 0),         // hsl(0, 0%, 0%)
            secondary_active: Rgb(214, 214, 214),       // hsl(44, 0%, 84%)
            muted: Rgb(240, 240, 240),                  // hsl(0, 0%, 94%)
            muted_foreground: Rgb(51, 51, 51),          // hsl(0, 0%, 20%)
            accent: Rgb(255, 204, 0),                   // hsl(48, 100%, 50%)
            accent_foreground: Rgb(0, 0, 0),            // hsl(0, 0%, 0%)
            destructive: Rgb(163, 0, 0),                // hsl(0, 100%, 32%)
            destructive_foreground: Rgb(255, 255, 255), // hsl(0, 0%, 100%)
            success: Rgb(0, 102, 34),                   // hsl(140, 100%, 20%)
            success_foreground: Rgb(255, 255, 255),     // hsl(0, 0%, 100%)
            warning: Rgb(143, 71, 0),                   // hsl(30, 100%, 28%)
            warning_foreground: Rgb(255, 255, 255),     // hsl(0, 0%, 100%)
            info: Rgb(0, 51, 153),                      // hsl(220, 100%, 30%)
            info_foreground: Rgb(255, 255, 255),        // hsl(0, 0%, 100%)
            border: Rgb(115, 115, 115),                 // hsl(0, 0%, 45%)
            border_strong: Rgb(0, 0, 0),                // hsl(0, 0%, 0%)
            ring: Rgb(0, 68, 204),                      // hsl(220, 100%, 40%)
            chart_1: Rgb(0, 54, 163),                   // hsl(220, 100%, 32%)
            chart_2: Rgb(163, 0, 0),                    // hsl(0, 100%, 32%)
            chart_3: Rgb(0, 102, 34),                   // hsl(140, 100%, 20%)
            chart_4: Rgb(143, 71, 0),                   // hsl(30, 100%, 28%)
            chart_5: Rgb(122, 0, 163),                  // hsl(285, 100%, 32%)
            code_keyword: Rgb(0, 54, 163),              // hsl(220, 100%, 32%)
            code_string: Rgb(163, 0, 0),                // hsl(0, 100%, 32%)
        },
    },
    Theme {
        name: "sepia",
        dark: false,
        fx_duration_ms: 220,
        palette: Palette {
            background: Rgb(246, 241, 233),             // hsl(38, 42%, 94%)
            foreground: Rgb(59, 40, 22),                // hsl(28, 45%, 16%)
            card: Rgb(251, 248, 244),                   // hsl(38, 50%, 97%)
            card_foreground: Rgb(59, 40, 22),           // hsl(28, 45%, 16%)
            popover: Rgb(253, 251, 247),                // hsl(38, 55%, 98%)
            popover_foreground: Rgb(59, 40, 22),        // hsl(28, 45%, 16%)
            primary: Rgb(126, 73, 37),                  // hsl(24, 55%, 32%)
            primary_foreground: Rgb(252, 248, 243),     // hsl(38, 55%, 97%)
            primary_hover: Rgb(109, 56, 18),            // hsl(25, 71%, 25%)
            primary_active: Rgb(92, 40, 0),             // hsl(26, 100%, 18%)
            primary_disabled: Rgb(156, 99, 64),         // hsl(23, 42%, 43%)
            secondary: Rgb(234, 226, 215),              // hsl(36, 30%, 88%)
            secondary_foreground: Rgb(79, 55, 34),      // hsl(28, 40%, 22%)
            secondary_active: Rgb(195, 188, 177),       // hsl(36, 13%, 73%)
            muted: Rgb(237, 231, 222),                  // hsl(36, 28%, 90%)
            muted_foreground: Rgb(112, 90, 72),         // hsl(28, 22%, 36%)
            accent: Rgb(239, 219, 200),                 // hsl(30, 55%, 86%)
            accent_foreground: Rgb(82, 45, 20),         // hsl(24, 60%, 20%)
            destructive: Rgb(155, 50, 39),              // hsl(6, 60%, 38%)
            destructive_foreground: Rgb(252, 248, 243), // hsl(38, 55%, 97%)
            success: Rgb(219, 230, 209),                // hsl(90, 30%, 86%)
            success_foreground: Rgb(46, 79, 23),        // hsl(95, 55%, 20%)
            warning: Rgb(243, 224, 186),                // hsl(40, 70%, 84%)
            warning_foreground: Rgb(123, 70, 10),       // hsl(32, 85%, 26%)
            info: Rgb(209, 223, 230),                   // hsl(200, 30%, 86%)
            info_foreground: Rgb(27, 73, 106),          // hsl(205, 60%, 26%)
            border: Rgb(222, 213, 201),                 // hsl(34, 25%, 83%)
            border_strong: Rgb(160, 133, 106),          // hsl(30, 22%, 52%)
            ring: Rgb(158, 91, 46),                     // hsl(24, 55%, 40%)
            chart_1: Rgb(150, 86, 44),                  // hsl(24, 55%, 38%)
            chart_2: Rgb(72, 103, 50),                  // hsl(95, 35%, 30%)
            chart_3: Rgb(52, 98, 121),                  // hsl(200, 40%, 34%)
            chart_4: Rgb(138, 66, 90),                  // hsl(340, 35%, 40%)
            chart_5: Rgb(135, 108, 29),                 // hsl(45, 65%, 32%)
            code_keyword: Rgb(150, 86, 44),             // hsl(24, 55%, 38%)
            code_string: Rgb(72, 103, 50),              // hsl(95, 35%, 30%)
        },
    },
    Theme {
        name: "blueprint",
        dark: true,
        fx_duration_ms: 160,
        palette: Palette {
            background: Rgb(11, 27, 50),              // hsl(215, 65%, 12%)
            foreground: Rgb(223, 242, 246),           // hsl(190, 55%, 92%)
            card: Rgb(16, 37, 65),                    // hsl(215, 60%, 16%)
            card_foreground: Rgb(223, 242, 246),      // hsl(190, 55%, 92%)
            popover: Rgb(20, 44, 77),                 // hsl(215, 58%, 19%)
            popover_foreground: Rgb(223, 242, 246),   // hsl(190, 55%, 92%)
            primary: Rgb(81, 210, 236),               // hsl(190, 80%, 62%)
            primary_foreground: Rgb(8, 23, 43),       // hsl(215, 70%, 10%)
            primary_hover: Rgb(102, 230, 255),        // hsl(190, 100%, 70%)
            primary_active: Rgb(122, 251, 255),       // hsl(182, 100%, 74%)
            primary_disabled: Rgb(40, 180, 204),      // hsl(189, 67%, 48%)
            secondary: Rgb(34, 57, 89),               // hsl(215, 45%, 24%)
            secondary_foreground: Rgb(211, 234, 238), // hsl(190, 45%, 88%)
            secondary_active: Rgb(65, 89, 124),       // hsl(215, 31%, 37%)
            muted: Rgb(34, 52, 79),                   // hsl(215, 40%, 22%)
            muted_foreground: Rgb(162, 194, 205),     // hsl(195, 30%, 72%)
            accent: Rgb(240, 167, 66),                // hsl(35, 85%, 60%)
            accent_foreground: Rgb(48, 26, 3),        // hsl(30, 90%, 10%)
            destructive: Rgb(226, 95, 90),            // hsl(2, 70%, 62%)
            destructive_foreground: Rgb(41, 10, 10),  // hsl(0, 60%, 10%)
            success: Rgb(30, 103, 78),                // hsl(160, 55%, 26%)
            success_foreground: Rgb(222, 247, 239),   // hsl(160, 60%, 92%)
            warning: Rgb(121, 80, 21),                // hsl(35, 70%, 28%)
            warning_foreground: Rgb(251, 239, 218),   // hsl(38, 80%, 92%)
            info: Rgb(27, 80, 106),                   // hsl(200, 60%, 26%)
            info_foreground: Rgb(220, 242, 249),      // hsl(195, 70%, 92%)
            border: Rgb(40, 66, 93),                  // hsl(210, 40%, 26%)
            border_strong: Rgb(100, 164, 196),        // hsl(200, 45%, 58%)
            ring: Rgb(81, 210, 236),                  // hsl(190, 80%, 62%)
            chart_1: Rgb(81, 210, 236),               // hsl(190, 80%, 62%)
            chart_2: Rgb(240, 167, 66),               // hsl(35, 85%, 60%)
            chart_3: Rgb(77, 203, 161),               // hsl(160, 55%, 55%)
            chart_4: Rgb(194, 133, 224),              // hsl(280, 60%, 70%)
            chart_5: Rgb(229, 112, 108),              // hsl(2, 70%, 66%)
            code_keyword: Rgb(81, 210, 236),          // hsl(190, 80%, 62%)
            code_string: Rgb(240, 167, 66),           // hsl(35, 85%, 60%)
        },
    },
    Theme {
        name: "solstice",
        dark: true,
        fx_duration_ms: 240,
        palette: Palette {
            background: Rgb(29, 24, 22),              // hsl(20, 14%, 10%)
            foreground: Rgb(237, 231, 222),           // hsl(35, 30%, 90%)
            card: Rgb(41, 34, 31),                    // hsl(20, 14%, 14%)
            card_foreground: Rgb(237, 231, 222),      // hsl(35, 30%, 90%)
            popover: Rgb(49, 41, 37),                 // hsl(20, 14%, 17%)
            popover_foreground: Rgb(237, 231, 222),   // hsl(35, 30%, 90%)
            primary: Rgb(239, 142, 57),               // hsl(28, 85%, 58%)
            primary_foreground: Rgb(41, 22, 10),      // hsl(24, 60%, 10%)
            primary_hover: Rgb(255, 160, 77),         // hsl(28, 100%, 65%)
            primary_active: Rgb(243, 184, 124),       // hsl(30, 83%, 72%)
            primary_disabled: Rgb(207, 113, 12),      // hsl(31, 89%, 43%)
            secondary: Rgb(64, 53, 48),               // hsl(20, 14%, 22%)
            secondary_foreground: Rgb(228, 221, 210), // hsl(35, 25%, 86%)
            secondary_active: Rgb(98, 86, 80),        // hsl(20, 10%, 35%)
            muted: Rgb(57, 49, 45),                   // hsl(20, 12%, 20%)
            muted_foreground: Rgb(192, 179, 165),     // hsl(32, 18%, 70%)
            accent: Rgb(212, 85, 53),                 // hsl(12, 65%, 52%)
            accent_foreground: Rgb(35, 13, 6),        // hsl(15, 70%, 8%)
            destructive: Rgb(219, 87, 87),            // hsl(0, 65%, 60%)
            destructive_foreground: Rgb(33, 8, 8),    // hsl(0, 60%, 8%)
            success: Rgb(57, 86, 37),                 // hsl(95, 40%, 24%)
            success_foreground: Rgb(230, 241, 218),   // hsl(90, 45%, 90%)
            warning: Rgb(113, 79, 20),                // hsl(38, 70%, 26%)
            warning_foreground: Rgb(251, 240, 218),   // hsl(40, 80%, 92%)
            info: Rgb(40, 75, 93),                    // hsl(200, 40%, 26%)
            info_foreground: Rgb(223, 239, 246),      // hsl(198, 55%, 92%)
            border: Rgb(70, 59, 53),                  // hsl(22, 14%, 24%)
            border_strong: Rgb(163, 140, 117),        // hsl(30, 20%, 55%)
            ring: Rgb(239, 142, 57),                  // hsl(28, 85%, 58%)
            chart_1: Rgb(239, 142, 57),               // hsl(28, 85%, 58%)
            chart_2: Rgb(218, 106, 78),               // hsl(12, 65%, 58%)
            chart_3: Rgb(221, 180, 60),               // hsl(45, 70%, 55%)
            chart_4: Rgb(124, 182, 84),               // hsl(95, 40%, 52%)
            chart_5: Rgb(197, 119, 171),              // hsl(320, 40%, 62%)
            code_keyword: Rgb(239, 142, 57),          // hsl(28, 85%, 58%)
            code_string: Rgb(218, 106, 78),           // hsl(12, 65%, 58%)
        },
    },
    Theme {
        name: "brutalism",
        dark: false,
        fx_duration_ms: 100,
        palette: Palette {
            background: Rgb(255, 252, 240),             // hsl(50, 100%, 97%)
            foreground: Rgb(18, 18, 18),                // hsl(0, 0%, 7%)
            card: Rgb(255, 255, 255),                   // hsl(0, 0%, 100%)
            card_foreground: Rgb(18, 18, 18),           // hsl(0, 0%, 7%)
            popover: Rgb(255, 255, 255),                // hsl(0, 0%, 100%)
            popover_foreground: Rgb(18, 18, 18),        // hsl(0, 0%, 7%)
            primary: Rgb(18, 18, 18),                   // hsl(0, 0%, 7%)
            primary_foreground: Rgb(255, 214, 51),      // hsl(48, 100%, 60%)
            primary_hover: Rgb(5, 5, 5),                // hsl(44, 0%, 2%)
            primary_active: Rgb(0, 0, 0),               // hsl(44, 0%, 0%)
            primary_disabled: Rgb(38, 38, 38),          // hsl(44, 0%, 15%)
            secondary: Rgb(255, 214, 51),               // hsl(48, 100%, 60%)
            secondary_foreground: Rgb(18, 18, 18),      // hsl(0, 0%, 7%)
            secondary_active: Rgb(214, 175, 0),         // hsl(49, 100%, 42%)
            muted: Rgb(239, 237, 225),                  // hsl(50, 30%, 91%)
            muted_foreground: Rgb(71, 71, 71),          // hsl(0, 0%, 28%)
            accent: Rgb(185, 166, 242),                 // hsl(255, 75%, 80%)
            accent_foreground: Rgb(18, 18, 18),         // hsl(0, 0%, 7%)
            destructive: Rgb(189, 15, 15),              // hsl(0, 85%, 40%)
            destructive_foreground: Rgb(255, 252, 240), // hsl(50, 100%, 97%)
            success: Rgb(141, 226, 169),                // hsl(140, 60%, 72%)
            success_foreground: Rgb(18, 18, 18),        // hsl(0, 0%, 7%)
            warning: Rgb(255, 183, 82),                 // hsl(35, 100%, 66%)
            warning_foreground: Rgb(18, 18, 18),        // hsl(0, 0%, 7%)
            info: Rgb(148, 207, 249),                   // hsl(205, 90%, 78%)
            info_foreground: Rgb(18, 18, 18),           // hsl(0, 0%, 7%)
            border: Rgb(18, 18, 18),                    // hsl(0, 0%, 7%)
            border_strong: Rgb(18, 18, 18),             // hsl(0, 0%, 7%)
            ring: Rgb(18, 18, 18),                      // hsl(0, 0%, 7%)
            chart_1: Rgb(184, 138, 0),                  // hsl(45, 100%, 36%)
            chart_2: Rgb(212, 17, 17),                  // hsl(0, 85%, 45%)
            chart_3: Rgb(96, 59, 206),                  // hsl(255, 60%, 52%)
            chart_4: Rgb(9, 106, 174),                  // hsl(205, 90%, 36%)
            chart_5: Rgb(29, 114, 57),                  // hsl(140, 60%, 28%)
            code_keyword: Rgb(148, 111, 0),             // hsl(45, 100%, 29%)
            code_string: Rgb(212, 17, 17),              // hsl(0, 85%, 45%)
        },
    },
    Theme {
        name: "deco",
        dark: true,
        fx_duration_ms: 160,
        palette: Palette {
            background: Rgb(15, 22, 26),              // hsl(200, 25%, 8%)
            foreground: Rgb(243, 232, 206),           // hsl(42, 60%, 88%)
            card: Rgb(22, 30, 34),                    // hsl(200, 22%, 11%)
            card_foreground: Rgb(243, 232, 206),      // hsl(42, 60%, 88%)
            popover: Rgb(29, 38, 43),                 // hsl(200, 20%, 14%)
            popover_foreground: Rgb(243, 232, 206),   // hsl(42, 60%, 88%)
            primary: Rgb(212, 167, 53),               // hsl(43, 65%, 52%)
            primary_foreground: Rgb(14, 22, 27),      // hsl(200, 30%, 8%)
            primary_hover: Rgb(232, 184, 74),         // hsl(42, 77%, 60%)
            primary_active: Rgb(252, 205, 95),        // hsl(42, 96%, 68%)
            primary_disabled: Rgb(184, 141, 0),       // hsl(46, 100%, 36%)
            secondary: Rgb(38, 49, 54),               // hsl(200, 18%, 18%)
            secondary_foreground: Rgb(237, 226, 201), // hsl(42, 50%, 86%)
            secondary_active: Rgb(68, 79, 85),        // hsl(200, 11%, 30%)
            muted: Rgb(31, 41, 45),                   // hsl(200, 18%, 15%)
            muted_foreground: Rgb(205, 192, 162),     // hsl(42, 30%, 72%)
            accent: Rgb(33, 131, 106),                // hsl(165, 60%, 32%)
            accent_foreground: Rgb(6, 24, 20),        // hsl(165, 60%, 6%)
            destructive: Rgb(234, 62, 76),            // hsl(355, 80%, 58%)
            destructive_foreground: Rgb(33, 8, 10),   // hsl(355, 60%, 8%)
            success: Rgb(39, 104, 71),                // hsl(150, 45%, 28%)
            success_foreground: Rgb(217, 242, 230),   // hsl(150, 50%, 90%)
            warning: Rgb(130, 91, 23),                // hsl(38, 70%, 30%)
            warning_foreground: Rgb(251, 240, 218),   // hsl(40, 80%, 92%)
            info: Rgb(34, 77, 119),                   // hsl(210, 55%, 30%)
            info_foreground: Rgb(222, 237, 247),      // hsl(205, 60%, 92%)
            border: Rgb(42, 54, 60),                  // hsl(200, 18%, 20%)
            border_strong: Rgb(172, 147, 83),         // hsl(43, 35%, 50%)
            ring: Rgb(212, 167, 53),                  // hsl(43, 65%, 52%)
            chart_1: Rgb(215, 173, 66),               // hsl(43, 65%, 55%)
            chart_2: Rgb(52, 178, 146),               // hsl(165, 55%, 45%)
            chart_3: Rgb(82, 153, 224),               // hsl(210, 70%, 60%)
            chart_4: Rgb(230, 76, 89),                // hsl(355, 75%, 60%)
            chart_5: Rgb(216, 194, 151),              // hsl(40, 45%, 72%)
            code_keyword: Rgb(215, 173, 66),          // hsl(43, 65%, 55%)
            code_string: Rgb(52, 178, 146),           // hsl(165, 55%, 45%)
        },
    },
    Theme {
        name: "phantom",
        dark: true,
        fx_duration_ms: 120,
        palette: Palette {
            background: Rgb(10, 10, 10),              // hsl(0, 0%, 4%)
            foreground: Rgb(250, 250, 250),           // hsl(0, 0%, 98%)
            card: Rgb(23, 23, 23),                    // hsl(0, 0%, 9%)
            card_foreground: Rgb(250, 250, 250),      // hsl(0, 0%, 98%)
            popover: Rgb(33, 33, 33),                 // hsl(0, 0%, 13%)
            popover_foreground: Rgb(250, 250, 250),   // hsl(0, 0%, 98%)
            primary: Rgb(255, 41, 59),                // hsl(355, 100%, 58%)
            primary_foreground: Rgb(10, 10, 10),      // hsl(0, 0%, 4%)
            primary_hover: Rgb(255, 71, 81),          // hsl(357, 100%, 64%)
            primary_active: Rgb(234, 115, 113),       // hsl(1, 74%, 68%)
            primary_disabled: Rgb(219, 0, 29),        // hsl(352, 100%, 43%)
            secondary: Rgb(41, 41, 41),               // hsl(0, 0%, 16%)
            secondary_foreground: Rgb(250, 250, 250), // hsl(0, 0%, 98%)
            secondary_active: Rgb(71, 71, 71),        // hsl(44, 0%, 28%)
            muted: Rgb(31, 31, 31),                   // hsl(0, 0%, 12%)
            muted_foreground: Rgb(173, 173, 173),     // hsl(0, 0%, 68%)
            accent: Rgb(219, 219, 219),               // hsl(0, 0%, 86%)
            accent_foreground: Rgb(10, 10, 10),       // hsl(0, 0%, 4%)
            destructive: Rgb(255, 41, 59),            // hsl(355, 100%, 58%)
            destructive_foreground: Rgb(10, 10, 10),  // hsl(0, 0%, 4%)
            success: Rgb(27, 106, 53),                // hsl(140, 60%, 26%)
            success_foreground: Rgb(222, 247, 231),   // hsl(140, 60%, 92%)
            warning: Rgb(133, 99, 0),                 // hsl(45, 100%, 26%)
            warning_foreground: Rgb(255, 245, 214),   // hsl(45, 100%, 92%)
            info: Rgb(17, 87, 156),                   // hsl(210, 80%, 34%)
            info_foreground: Rgb(223, 237, 251),      // hsl(210, 80%, 93%)
            border: Rgb(56, 56, 56),                  // hsl(0, 0%, 22%)
            border_strong: Rgb(153, 153, 153),        // hsl(0, 0%, 60%)
            ring: Rgb(255, 41, 59),                   // hsl(355, 100%, 58%)
            chart_1: Rgb(255, 41, 59),                // hsl(355, 100%, 58%)
            chart_2: Rgb(230, 230, 230),              // hsl(0, 0%, 90%)
            chart_3: Rgb(140, 140, 140),              // hsl(0, 0%, 55%)
            chart_4: Rgb(207, 23, 38),                // hsl(355, 80%, 45%)
            chart_5: Rgb(255, 198, 26),               // hsl(45, 100%, 55%)
            code_keyword: Rgb(255, 41, 59),           // hsl(355, 100%, 58%)
            code_string: Rgb(230, 230, 230),          // hsl(0, 0%, 90%)
        },
    },
    Theme {
        name: "shade-light",
        dark: false,
        fx_duration_ms: 180,
        palette: Palette {
            background: Rgb(253, 246, 226),             // hsl(44, 87%, 94%)
            foreground: Rgb(79, 99, 105),               // hsl(194, 14%, 36%)
            card: Rgb(254, 250, 241),                   // hsl(44, 87%, 97%)
            card_foreground: Rgb(79, 99, 105),          // hsl(194, 14%, 36%)
            popover: Rgb(255, 254, 250),                // hsl(44, 90%, 99%)
            popover_foreground: Rgb(79, 99, 105),       // hsl(194, 14%, 36%)
            primary: Rgb(29, 108, 165),                 // hsl(205, 70%, 38%)
            primary_foreground: Rgb(254, 249, 236),     // hsl(44, 87%, 96%)
            primary_hover: Rgb(0, 91, 148),             // hsl(203, 100%, 29%)
            primary_active: Rgb(0, 74, 128),            // hsl(205, 100%, 25%)
            primary_disabled: Rgb(61, 136, 194),        // hsl(206, 52%, 50%)
            secondary: Rgb(237, 231, 212),              // hsl(46, 42%, 88%)
            secondary_foreground: Rgb(42, 64, 70),      // hsl(194, 25%, 22%)
            secondary_active: Rgb(199, 193, 174),       // hsl(46, 18%, 73%)
            muted: Rgb(240, 235, 219),                  // hsl(46, 40%, 90%)
            muted_foreground: Rgb(86, 107, 113),        // hsl(194, 14%, 39%)
            accent: Rgb(37, 147, 138),                  // hsl(175, 60%, 36%)
            accent_foreground: Rgb(254, 249, 236),      // hsl(44, 87%, 96%)
            destructive: Rgb(183, 34, 31),              // hsl(1, 71%, 42%)
            destructive_foreground: Rgb(254, 249, 236), // hsl(44, 87%, 96%)
            success: Rgb(97, 112, 0),                   // hsl(68, 100%, 22%)
            success_foreground: Rgb(252, 252, 227),     // hsl(60, 80%, 94%)
            warning: Rgb(143, 107, 0),                  // hsl(45, 100%, 28%)
            warning_foreground: Rgb(252, 246, 227),     // hsl(45, 80%, 94%)
            info: Rgb(26, 97, 147),                     // hsl(205, 70%, 34%)
            info_foreground: Rgb(254, 249, 236),        // hsl(44, 87%, 96%)
            border: Rgb(231, 223, 197),                 // hsl(46, 42%, 84%)
            border_strong: Rgb(113, 132, 132),          // hsl(180, 8%, 48%)
            ring: Rgb(29, 108, 165),                    // hsl(205, 70%, 38%)
            chart_1: Rgb(29, 108, 165),                 // hsl(205, 70%, 38%)
            chart_2: Rgb(163, 122, 0),                  // hsl(45, 100%, 32%)
            chart_3: Rgb(201, 44, 120),                 // hsl(331, 64%, 48%)
            chart_4: Rgb(36, 138, 129),                 // hsl(175, 59%, 34%)
            chart_5: Rgb(95, 99, 191),                  // hsl(237, 43%, 56%)
            code_keyword: Rgb(29, 108, 165),            // hsl(205, 70%, 38%)
            code_string: Rgb(143, 107, 0),              // hsl(45, 100%, 28%)
        },
    },
    Theme {
        name: "shade-dark",
        dark: true,
        fx_duration_ms: 180,
        palette: Palette {
            background: Rgb(0, 45, 56),               // hsl(192, 100%, 11%)
            foreground: Rgb(156, 169, 171),           // hsl(186, 8%, 64%)
            card: Rgb(7, 53, 65),                     // hsl(192, 81%, 14%)
            card_foreground: Rgb(156, 169, 171),      // hsl(186, 8%, 64%)
            popover: Rgb(17, 59, 69),                 // hsl(192, 60%, 17%)
            popover_foreground: Rgb(156, 169, 171),   // hsl(186, 8%, 64%)
            primary: Rgb(80, 165, 226),               // hsl(205, 72%, 60%)
            primary_foreground: Rgb(0, 45, 56),       // hsl(192, 100%, 11%)
            primary_hover: Rgb(100, 186, 247),        // hsl(205, 90%, 68%)
            primary_active: Rgb(117, 205, 255),       // hsl(202, 100%, 73%)
            primary_disabled: Rgb(49, 137, 196),      // hsl(204, 60%, 48%)
            secondary: Rgb(18, 62, 73),               // hsl(192, 60%, 18%)
            secondary_foreground: Rgb(199, 209, 209), // hsl(180, 10%, 80%)
            secondary_active: Rgb(52, 94, 106),       // hsl(193, 34%, 31%)
            muted: Rgb(11, 54, 65),                   // hsl(192, 70%, 15%)
            muted_foreground: Rgb(150, 164, 166),     // hsl(186, 8%, 62%)
            accent: Rgb(42, 162, 152),                // hsl(175, 59%, 40%)
            accent_foreground: Rgb(0, 45, 56),        // hsl(192, 100%, 11%)
            destructive: Rgb(242, 97, 95),            // hsl(1, 85%, 66%)
            destructive_foreground: Rgb(41, 11, 10),  // hsl(1, 60%, 10%)
            success: Rgb(138, 156, 17),               // hsl(68, 80%, 34%)
            success_foreground: Rgb(29, 33, 8),       // hsl(68, 60%, 8%)
            warning: Rgb(173, 130, 0),                // hsl(45, 100%, 34%)
            warning_foreground: Rgb(37, 29, 4),       // hsl(45, 80%, 8%)
            info: Rgb(21, 80, 121),                   // hsl(205, 70%, 28%)
            info_foreground: Rgb(222, 237, 247),      // hsl(205, 60%, 92%)
            border: Rgb(26, 66, 77),                  // hsl(192, 50%, 20%)
            border_strong: Rgb(110, 137, 145),        // hsl(194, 14%, 50%)
            ring: Rgb(112, 184, 235),                 // hsl(205, 75%, 68%)
            chart_1: Rgb(80, 165, 226),               // hsl(205, 72%, 60%)
            chart_2: Rgb(230, 172, 0),                // hsl(45, 100%, 45%)
            chart_3: Rgb(216, 79, 146),               // hsl(331, 64%, 58%)
            chart_4: Rgb(42, 162, 152),               // hsl(175, 59%, 40%)
            chart_5: Rgb(127, 131, 204),              // hsl(237, 43%, 65%)
            code_keyword: Rgb(80, 165, 226),          // hsl(205, 72%, 60%)
            code_string: Rgb(230, 172, 0),            // hsl(45, 100%, 45%)
        },
    },
    Theme {
        name: "retro",
        dark: false,
        fx_duration_ms: 180,
        palette: Palette {
            background: Rgb(191, 191, 191),             // hsl(0, 0%, 75%)
            foreground: Rgb(26, 26, 26),                // hsl(0, 0%, 10%)
            card: Rgb(214, 214, 214),                   // hsl(0, 0%, 84%)
            card_foreground: Rgb(26, 26, 26),           // hsl(0, 0%, 10%)
            popover: Rgb(230, 230, 230),                // hsl(0, 0%, 90%)
            popover_foreground: Rgb(26, 26, 26),        // hsl(0, 0%, 10%)
            primary: Rgb(0, 0, 128),                    // hsl(240, 100%, 25%)
            primary_foreground: Rgb(255, 255, 255),     // hsl(0, 0%, 100%)
            primary_hover: Rgb(5, 0, 107),              // hsl(243, 100%, 21%)
            primary_active: Rgb(12, 16, 70),            // hsl(236, 71%, 16%)
            primary_disabled: Rgb(5, 43, 158),          // hsl(225, 94%, 32%)
            secondary: Rgb(222, 222, 222),              // hsl(0, 0%, 87%)
            secondary_foreground: Rgb(26, 26, 26),      // hsl(0, 0%, 10%)
            secondary_active: Rgb(184, 184, 184),       // hsl(44, 0%, 72%)
            muted: Rgb(204, 204, 204),                  // hsl(0, 0%, 80%)
            muted_foreground: Rgb(64, 64, 64),          // hsl(0, 0%, 25%)
            accent: Rgb(0, 102, 102),                   // hsl(180, 100%, 20%)
            accent_foreground: Rgb(255, 255, 255),      // hsl(0, 0%, 100%)
            destructive: Rgb(128, 0, 0),                // hsl(0, 100%, 25%)
            destructive_foreground: Rgb(255, 255, 255), // hsl(0, 0%, 100%)
            success: Rgb(0, 102, 0),                    // hsl(120, 100%, 20%)
            success_foreground: Rgb(255, 255, 255),     // hsl(0, 0%, 100%)
            warning: Rgb(255, 213, 0),                  // hsl(50, 100%, 50%)
            warning_foreground: Rgb(26, 26, 26),        // hsl(0, 0%, 10%)
            info: Rgb(0, 77, 153),                      // hsl(210, 100%, 30%)
            info_foreground: Rgb(255, 255, 255),        // hsl(0, 0%, 100%)
            border: Rgb(128, 128, 128),                 // hsl(0, 0%, 50%)
            border_strong: Rgb(97, 97, 97),             // hsl(0, 0%, 38%)
            ring: Rgb(0, 0, 128),                       // hsl(240, 100%, 25%)
            chart_1: Rgb(0, 0, 128),                    // hsl(240, 100%, 25%)
            chart_2: Rgb(0, 102, 102),                  // hsl(180, 100%, 20%)
            chart_3: Rgb(128, 0, 0),                    // hsl(0, 100%, 25%)
            chart_4: Rgb(128, 0, 128),                  // hsl(300, 100%, 25%)
            chart_5: Rgb(0, 102, 0),                    // hsl(120, 100%, 20%)
            code_keyword: Rgb(0, 0, 128),               // hsl(240, 100%, 25%)
            code_string: Rgb(0, 102, 102),              // hsl(180, 100%, 20%)
        },
    },
    Theme {
        name: "grotesk",
        dark: false,
        fx_duration_ms: 120,
        palette: Palette {
            background: Rgb(255, 255, 255),             // hsl(0, 0%, 100%)
            foreground: Rgb(18, 18, 18),                // hsl(0, 0%, 7%)
            card: Rgb(255, 255, 255),                   // hsl(0, 0%, 100%)
            card_foreground: Rgb(18, 18, 18),           // hsl(0, 0%, 7%)
            popover: Rgb(255, 255, 255),                // hsl(0, 0%, 100%)
            popover_foreground: Rgb(18, 18, 18),        // hsl(0, 0%, 7%)
            primary: Rgb(224, 6, 24),                   // hsl(355, 95%, 45%)
            primary_foreground: Rgb(255, 255, 255),     // hsl(0, 0%, 100%)
            primary_hover: Rgb(204, 0, 0),              // hsl(0, 100%, 40%)
            primary_active: Rgb(172, 31, 21),           // hsl(4, 78%, 38%)
            primary_disabled: Rgb(255, 59, 56),         // hsl(1, 100%, 61%)
            secondary: Rgb(240, 240, 240),              // hsl(0, 0%, 94%)
            secondary_foreground: Rgb(18, 18, 18),      // hsl(0, 0%, 7%)
            secondary_active: Rgb(201, 201, 201),       // hsl(44, 0%, 79%)
            muted: Rgb(245, 245, 245),                  // hsl(0, 0%, 96%)
            muted_foreground: Rgb(102, 102, 102),       // hsl(0, 0%, 40%)
            accent: Rgb(18, 18, 18),                    // hsl(0, 0%, 7%)
            accent_foreground: Rgb(255, 255, 255),      // hsl(0, 0%, 100%)
            destructive: Rgb(199, 5, 21),               // hsl(355, 95%, 40%)
            destructive_foreground: Rgb(255, 255, 255), // hsl(0, 0%, 100%)
            success: Rgb(27, 106, 66),                  // hsl(150, 60%, 26%)
            success_foreground: Rgb(255, 255, 255),     // hsl(0, 0%, 100%)
            warning: Rgb(194, 129, 0),                  // hsl(40, 100%, 38%)
            warning_foreground: Rgb(18, 18, 18),        // hsl(0, 0%, 7%)
            info: Rgb(31, 78, 173),                     // hsl(220, 70%, 40%)
            info_foreground: Rgb(255, 255, 255),        // hsl(0, 0%, 100%)
            border: Rgb(217, 217, 217),                 // hsl(0, 0%, 85%)
            border_strong: Rgb(18, 18, 18),             // hsl(0, 0%, 7%)
            ring: Rgb(224, 6, 24),                      // hsl(355, 95%, 45%)
            chart_1: Rgb(224, 6, 24),                   // hsl(355, 95%, 45%)
            chart_2: Rgb(18, 18, 18),                   // hsl(0, 0%, 7%)
            chart_3: Rgb(115, 115, 115),                // hsl(0, 0%, 45%)
            chart_4: Rgb(31, 78, 173),                  // hsl(220, 70%, 40%)
            chart_5: Rgb(194, 129, 0),                  // hsl(40, 100%, 38%)
            code_keyword: Rgb(224, 6, 24),              // hsl(355, 95%, 45%)
            code_string: Rgb(18, 18, 18),               // hsl(0, 0%, 7%)
        },
    },
    Theme {
        name: "lapis",
        dark: true,
        fx_duration_ms: 220,
        palette: Palette {
            background: Rgb(27, 42, 106),             // hsl(228, 60%, 26%)
            foreground: Rgb(242, 233, 212),           // hsl(42, 55%, 89%)
            card: Rgb(34, 52, 124),                   // hsl(228, 57%, 31%)
            card_foreground: Rgb(242, 233, 212),      // hsl(42, 55%, 89%)
            popover: Rgb(42, 62, 141),                // hsl(228, 54%, 36%)
            popover_foreground: Rgb(242, 233, 212),   // hsl(42, 55%, 89%)
            primary: Rgb(213, 165, 42),               // hsl(43, 67%, 50%)
            primary_foreground: Rgb(12, 20, 49),      // hsl(228, 60%, 12%)
            primary_hover: Rgb(233, 183, 68),         // hsl(42, 79%, 59%)
            primary_active: Rgb(252, 204, 89),        // hsl(42, 97%, 67%)
            primary_disabled: Rgb(184, 138, 0),       // hsl(45, 100%, 36%)
            secondary: Rgb(43, 61, 130),              // hsl(228, 50%, 34%)
            secondary_foreground: Rgb(242, 233, 212), // hsl(42, 55%, 89%)
            secondary_active: Rgb(73, 95, 167),       // hsl(226, 39%, 47%)
            muted: Rgb(45, 60, 118),                  // hsl(228, 45%, 32%)
            muted_foreground: Rgb(169, 175, 209),     // hsl(230, 30%, 74%)
            accent: Rgb(226, 69, 54),                 // hsl(5, 75%, 55%)
            accent_foreground: Rgb(33, 10, 8),        // hsl(5, 60%, 8%)
            destructive: Rgb(247, 121, 110),          // hsl(5, 90%, 70%)
            destructive_foreground: Rgb(33, 10, 8),   // hsl(5, 60%, 8%)
            success: Rgb(46, 107, 97),                // hsl(170, 40%, 30%)
            success_foreground: Rgb(242, 233, 212),   // hsl(42, 55%, 89%)
            warning: Rgb(122, 92, 31),                // hsl(40, 60%, 30%)
            warning_foreground: Rgb(242, 233, 212),   // hsl(42, 55%, 89%)
            info: Rgb(33, 90, 131),                   // hsl(205, 60%, 32%)
            info_foreground: Rgb(242, 233, 212),      // hsl(42, 55%, 89%)
            border: Rgb(50, 67, 133),                 // hsl(228, 45%, 36%)
            border_strong: Rgb(188, 156, 78),         // hsl(43, 45%, 52%)
            ring: Rgb(213, 165, 42),                  // hsl(43, 67%, 50%)
            chart_1: Rgb(213, 165, 42),               // hsl(43, 67%, 50%)
            chart_2: Rgb(236, 94, 81),                // hsl(5, 80%, 62%)
            chart_3: Rgb(64, 191, 170),               // hsl(170, 50%, 50%)
            chart_4: Rgb(232, 215, 176),              // hsl(42, 55%, 80%)
            chart_5: Rgb(210, 121, 166),              // hsl(330, 50%, 65%)
            code_keyword: Rgb(213, 165, 42),          // hsl(43, 67%, 50%)
            code_string: Rgb(241, 136, 126),          // hsl(5, 80%, 72%)
        },
    },
    Theme {
        name: "nostromo",
        dark: false,
        fx_duration_ms: 160,
        palette: Palette {
            background: Rgb(215, 203, 183),             // hsl(38, 28%, 78%)
            foreground: Rgb(43, 37, 34),                // hsl(24, 12%, 15%)
            card: Rgb(225, 215, 199),                   // hsl(38, 30%, 83%)
            card_foreground: Rgb(43, 37, 34),           // hsl(24, 12%, 15%)
            popover: Rgb(235, 227, 214),                // hsl(38, 35%, 88%)
            popover_foreground: Rgb(43, 37, 34),        // hsl(24, 12%, 15%)
            primary: Rgb(49, 42, 38),                   // hsl(24, 12%, 17%)
            primary_foreground: Rgb(237, 232, 222),     // hsl(38, 30%, 90%)
            primary_hover: Rgb(33, 27, 23),             // hsl(24, 17%, 11%)
            primary_active: Rgb(20, 14, 11),            // hsl(24, 30%, 6%)
            primary_disabled: Rgb(72, 65, 61),          // hsl(24, 8%, 26%)
            secondary: Rgb(195, 183, 162),              // hsl(38, 22%, 70%)
            secondary_foreground: Rgb(43, 37, 34),      // hsl(24, 12%, 15%)
            secondary_active: Rgb(156, 145, 124),       // hsl(38, 14%, 55%)
            muted: Rgb(200, 190, 172),                  // hsl(38, 20%, 73%)
            muted_foreground: Rgb(84, 77, 69),          // hsl(30, 10%, 30%)
            accent: Rgb(200, 78, 30),                   // hsl(17, 74%, 45%)
            accent_foreground: Rgb(237, 232, 222),      // hsl(38, 30%, 90%)
            destructive: Rgb(129, 33, 14),              // hsl(10, 80%, 28%)
            destructive_foreground: Rgb(237, 232, 222), // hsl(38, 30%, 90%)
            success: Rgb(46, 96, 63),                   // hsl(140, 35%, 28%)
            success_foreground: Rgb(237, 232, 222),     // hsl(38, 30%, 90%)
            warning: Rgb(136, 89, 7),                   // hsl(38, 90%, 28%)
            warning_foreground: Rgb(237, 232, 222),     // hsl(38, 30%, 90%)
            info: Rgb(45, 88, 118),                     // hsl(205, 45%, 32%)
            info_foreground: Rgb(237, 232, 222),        // hsl(38, 30%, 90%)
            border: Rgb(176, 163, 141),                 // hsl(38, 18%, 62%)
            border_strong: Rgb(120, 107, 94),           // hsl(30, 12%, 42%)
            ring: Rgb(49, 42, 38),                      // hsl(24, 12%, 17%)
            chart_1: Rgb(169, 66, 25),                  // hsl(17, 74%, 38%)
            chart_2: Rgb(43, 37, 34),                   // hsl(24, 12%, 15%)
            chart_3: Rgb(143, 104, 36),                 // hsl(38, 60%, 35%)
            chart_4: Rgb(50, 103, 68),                  // hsl(140, 35%, 30%)
            chart_5: Rgb(49, 96, 129),                  // hsl(205, 45%, 35%)
            code_keyword: Rgb(160, 62, 24),             // hsl(17, 74%, 36%)
            code_string: Rgb(43, 37, 34),               // hsl(24, 12%, 15%)
        },
    },
    Theme {
        name: "titanium",
        dark: true,
        fx_duration_ms: 60,
        palette: Palette {
            background: Rgb(21, 25, 30),              // hsl(216, 16%, 10%)
            foreground: Rgb(237, 240, 242),           // hsl(210, 16%, 94%)
            card: Rgb(33, 38, 43),                    // hsl(214, 13%, 15%)
            card_foreground: Rgb(237, 240, 242),      // hsl(210, 16%, 94%)
            popover: Rgb(37, 43, 49),                 // hsl(214, 14%, 17%)
            popover_foreground: Rgb(237, 240, 242),   // hsl(210, 16%, 94%)
            primary: Rgb(217, 221, 227),              // hsl(212, 16%, 87%)
            primary_foreground: Rgb(22, 27, 34),      // hsl(216, 22%, 11%)
            primary_hover: Rgb(196, 203, 212),        // hsl(212, 16%, 80%)
            primary_active: Rgb(178, 188, 199),       // hsl(212, 16%, 74%)
            primary_disabled: Rgb(189, 193, 199),     // hsl(212, 8%, 76%)
            secondary: Rgb(28, 32, 38),               // hsl(216, 15%, 13%)
            secondary_foreground: Rgb(188, 193, 200), // hsl(212, 10%, 76%)
            secondary_active: Rgb(58, 63, 69),        // hsl(216, 9%, 25%)
            muted: Rgb(26, 30, 35),                   // hsl(216, 15%, 12%)
            muted_foreground: Rgb(137, 144, 154),     // hsl(214, 8%, 57%)
            accent: Rgb(55, 60, 67),                  // hsl(214, 10%, 24%)
            accent_foreground: Rgb(168, 178, 189),    // hsl(212, 14%, 70%)
            destructive: Rgb(243, 107, 73),           // hsl(12, 88%, 62%)
            destructive_foreground: Rgb(37, 15, 9),   // hsl(12, 60%, 9%)
            success: Rgb(23, 54, 43),                 // hsl(160, 40%, 15%)
            success_foreground: Rgb(54, 201, 152),    // hsl(160, 58%, 50%)
            warning: Rgb(64, 47, 17),                 // hsl(38, 58%, 16%)
            warning_foreground: Rgb(243, 181, 73),    // hsl(38, 88%, 62%)
            info: Rgb(22, 46, 65),                    // hsl(206, 50%, 17%)
            info_foreground: Rgb(148, 194, 230),      // hsl(206, 62%, 74%)
            border: Rgb(55, 60, 67),                  // hsl(214, 10%, 24%)
            border_strong: Rgb(92, 101, 112),         // hsl(214, 10%, 40%)
            ring: Rgb(82, 143, 224),                  // hsl(214, 70%, 60%)
            chart_1: Rgb(77, 147, 239),               // hsl(214, 84%, 62%)
            chart_2: Rgb(164, 102, 234),              // hsl(268, 76%, 66%)
            chart_3: Rgb(64, 215, 231),               // hsl(186, 78%, 58%)
            chart_4: Rgb(243, 107, 73),               // hsl(12, 88%, 62%)
            chart_5: Rgb(217, 221, 227),              // hsl(212, 16%, 87%)
            code_keyword: Rgb(77, 147, 239),          // hsl(214, 84%, 62%)
            code_string: Rgb(172, 116, 236),          // hsl(268, 76%, 69%)
        },
    },
];
